# -*- coding: utf-8 -*-
"""AnaliseCredito.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15MhtDnA1iUg3CLn2Cx-6oNJMDShpxOAG
"""

import pandas as pd
import plotly.express as px

"""Você trabalha em uma grande empresa de Cartão de Crédito e o diretor da empresa 
  percebeu que o número de clientes que cancelam seus cartões tem aumentado significativamente,
  causando prejuízos enormes para a empresa

O que fazer para evitar isso? Como saber quais pessoas que têm maior tendência a cancelar o cartão?

Passos:
- importar os dados
- excluir colunas irrelevantes
- visualizar a integridade dos dados
- limpar os dados
- gerar as visualizações para analisar
- gerar parecer
"""

clientes_df = pd.read_csv('/content/drive/MyDrive/Estudos/IntensivoPy/arquivosEntrada/ClientesBanco.csv', encoding='latin1')

display(clientes_df)

clientes_df = clientes_df.drop('CLIENTNUM', axis=1)

display(clientes_df)

"""### Tratamento e visão geral dos dados"""

display(clientes_df.info()) #tem 1 dado vazio, vamos deletá-lo
clientes_df = clientes_df.dropna()

display(clientes_df.describe()) #visão geral dos dados

"""### Visualizando os Dados"""

display(clientes_df['Categoria'].value_counts()) #exibindo a contagem por categoria
display(clientes_df['Categoria'].value_counts(normalize=True)) #contagem normalizada

"""- 16% dos clientes cancelaram seus cartões"""

def grafico_coluna_categoria(coluna, tabela):
  fig = px.histogram(tabela, x=coluna, color='Categoria') # color_discrete_sequence=['#e6ad12', '#02b013']
  fig.show()

for coluna in clientes_df:
  grafico_coluna_categoria(coluna, clientes_df)

"""### Análise

- inatividade 12m: os clientes inativos por períodos de 2 ~ 3 meses tendem a cancelar seus cartões

- contatos 12m: clientes com contatos entre 2 ~ vezes no período tendem a cancelar seus cartões

- limite: clientes com limites menores que 10k tendem a cancelar mais seus cartões

- limite consumido: clientes que utilizam pouco do seu limite representam grande parte dos cancelamentos

- limite disponível: clientes com pouco limite disponível tendem a cancelar mais seus cartões

- valor transações 12m: clientes com transações entre 0~3.5k cancelam mais cartões

- quantidade trasações 12m: clientes que geraram poucas transações nos últimos 12 meses cancelaram mais seus cartões

1.   Os clientes que estiveram inativos por períodos de 2~4 meses cancelaram
2.   Os clientes que entraram em contato conosco mais vezes cancelaram
3.   Clientes que utilizam pouco seu cartão tanto em quantidade de vezes quanto em valor cancelaram
4. em grande maioria, esses clientes eram clientes Blue

### Conclusões

Clientes com baixa utilização no cartão blue, são as que mais cancelam, oq pode ser pelo cartão não oferecer taxas adequadas a clientes que usam pouco o cartão.
Em resumo, quem tem pouco fluxo no cartão.
"""

cancelados_df = clientes_df.loc[clientes_df['Categoria'] == 'Cancelado', :]

fig = px.histogram(cancelados_df, x='Qtde Transacoes 12m', nbins=5)
fig.show()

fig = px.histogram(cancelados_df, x="Valor Transacoes 12m", nbins=7)
fig.show()

criticos_df = cancelados_df.loc[cancelados_df['Qtde Transacoes 12m'] < 60, :]
fig = px.histogram(criticos_df, x='Contatos 12m')
fig.show()

qtde_ultra_criticos = len(criticos_df.loc[criticos_df['Contatos 12m'] > 2, :])

percentual_criticos = qtde_ultra_criticos / len(cancelados_df)
print(f'{percentual_criticos:.1%}')

for coluna in cancelados_df:
  grafico_coluna_categoria(coluna, cancelados_df)